### ISSUE TITLE
DevRel : beginner resources how to contribute

### ISSUE THREAD

**Issue by Madhurchandran** [cncf/glossary#2426] opened 2023-09-21 16:12 UTC
#DevRel : - There should be page about DevRel engineer what they actually do in Orgainzation in glossary. [overview] 👍 
2. new term DevRel should be added in glossary.
#Devops : - provide some more information about Devops. 👍
`
``[tasklist]
### Tasks
```
![Screenshot (3)](https://github.com/cncf/glossary/assets/100069538/b4dca08f-7ebc-4b18-b30b-fcd439295853)

**Comment by jihoon-seo** [comment] 2023-09-23 00:17
Hello @Madhurchandran
This issue seems like a duplicate of #2427, so let me close this one.

**Closed by jihoon-seo** 2023-09-23 00:17 UTC
