### ISSUE TITLE
[English]: Declarative System

### ISSUE THREAD

**Issue by avinashupadhya99** [cncf/glossary#317] opened 2022-01-16 13:44 UTC
Add Declarative System to the glossary

**Comment by JasonMorgan** [comment] 2022-01-17 13:58
Can you provide some more context? Any examples you have of "Declarative System" being used would be handy.

**Comment by avinashupadhya99** [comment] 2022-01-17 15:55
Kubernetes is a Declarative System and a very important design principle of Kubernetes. When folks are trying to understand Kubernetes, understanding Declarative Systems becomes very important

**Comment by mayank-cse** [comment] 2022-02-04 15:37
@JasonMorgan  ma'am and @avinashupadhya99  sir
If the issue is not yet assigned to anyone, I would like to work on it

Thank You:)

**Comment by CathPag** [comment] 2022-02-07 13:06
Oops, sorry. You already have Container Storage Interface assigned. Please finish that one first before claiming a new term.

**Comment by Anujakumari** [comment] 2022-02-12 13:33
@CathPag
Can I work on this issue?

**Comment by CathPag** [comment] 2022-04-18 11:45
@Anujakumari, I'll open this PR up again since it's been assigned to you over in February and we haven't seen any PR yet.

**Comment by CathPag** [comment] 2022-06-17 13:27
We reviewed this issue and, since it doesn't meet the cloud native definition, we will not include this in the glossary.

**Closed by CathPag** 2022-06-17 13:27 UTC
Labels: good first issue, help wanted, lang/en, triage/not accepted
