### ISSUE TITLE
[zh] Localize 'observability'

### ISSUE THREAD

**Issue by Jacob953** [cncf/glossary#963] opened 2022-06-17 08:04 UTC
- [ ] Localize the content/en/observability.md to content/zh-cn/ in dev-zh.

**Comment by Superskyyy** [comment] 2022-06-23 16:51
https://github.com/cncf/glossary/issues/946 ACK :)

**Comment by hanyuancheung** [comment] 2022-07-15 09:15
Close cause of duplicate of #946

**Closed by hanyuancheung** 2022-07-15 09:15 UTC
Labels: lang/zh
