### ISSUE TITLE
Localise Horizontal Scaling page in Bengali

### ISSUE THREAD

**Issue by sajdakabir** [cncf/glossary#1866] opened 2023-04-01 14:32 UTC
The Bengali version of Horizontal Scaling is not available.
Link: https://glossary.cncf.io/horizontal-scaling/

@waleed318  Can you assign it to me? I want to work on this issue.

**Comment by waleed318** [comment] 2023-04-01 14:51
Hello sajdakabir, I am Urdu glossary approver please contact your bengali team. 🙂

**Comment by sajdakabir** [comment] 2023-04-09 07:21
@jihoon-seo Can I work on this issue?

**Comment by asem-hamid** [comment] 2024-01-14 05:44
@sajdakabir  already Localized by  someone

https://glossary.cncf.io/bn/horizontal-scaling/

**Comment by asem-hamid** [comment] 2024-01-21 14:36
@mitul3737 This issue is already fixed.

**Comment by sajibAdhi** [comment] 2024-02-01 05:10
The issue is already fixed in this [PR](https://github.com/cncf/glossary/pull/1814). I am closing this issue.

**Closed by sajibAdhi** 2024-02-01 05:10 UTC
Labels: lang/bn
