### ISSUE TITLE
Localise Zero Trust Architecture in hindi

### ISSUE THREAD

**Issue by Anuragwagh** [cncf/glossary#1609] opened 2023-01-10 13:42 UTC
Zero Trust Architecture is not in hindi 
https://glossary.cncf.io/zero-trust-architecture/

Assign me to work on it

**Comment by VamshiReddy02** [comment] 2023-01-14 17:00
can I work on this issue?

**Comment by jihoon-seo** [comment] 2023-01-31 04:40
This issue is a duplicate of #1354.

**Comment by Garima-Negi** [comment] 2023-02-07 07:15
closing since this is a duplicate PR. Issue for zero-trust architecture is already being worked on and a PR is under review

**Closed by Garima-Negi** 2023-02-07 07:15 UTC
Labels: duplicate, lang/hi, hold
