### ISSUE TITLE
[hi]Localize "Distributed Apps" in hindi

### ISSUE THREAD

**Issue by Aarav238** [cncf/glossary#1486] opened 2022-11-23 09:01 UTC

**Comment by Aarav238** [comment] 2022-11-23 09:02
Please Assign this issue to me. @Garima-Negi 
I want to work on this.

**Comment by Aarav238** [comment] 2022-11-23 13:28
I am working on it

**Comment by iamNoah1** [comment] 2022-11-23 13:45
@NitishKumar06 @Aarav238 please note that this is not the way this should work. Please make sure to read the contribution guide. Also if you want to help with localizing, the first step is not to just start working on a term. Instead, you should join the respective channel, say hi, and coordinate with the team regarding which work has to be done.

**Comment by Garima-Negi** [comment] 2023-01-08 16:41
duplicate of [https://github.com/cncf/glossary/issues/1315](https://github.com/cncf/glossary/issues/1315)
This term has already been added to dev-hi branch

**Closed by Garima-Negi** 2023-01-08 16:41 UTC
Labels: lang/hi
