### ISSUE TITLE
Cloud Computing For Hindi

### ISSUE THREAD

**Issue by gauravrattan** [cncf/glossary#1571] opened 2023-01-01 18:10 UTC
Cloud Computing  Hindi version is not available. If any one read in Hindi then he/she face issue.
Link=https://glossary.cncf.io/cloud-computing/

**Comment by VaibhavJangid** [comment] 2023-01-02 14:13
I would like to work on this term, I am a native Hindi speaker I would like to translate it into Hindi. If it hasn't been assigned to anyone then please assign it to me.

**Comment by Garima-Negi** [comment] 2023-01-07 17:05
duplicate of [https://github.com/cncf/glossary/issues/1005](https://github.com/cncf/glossary/issues/1005)

**Closed by Garima-Negi** 2023-01-07 17:05 UTC
Labels: lang/hi
