### ISSUE TITLE
[hi]  Localize `Zero Trust Architecture.md` to Hindi.

### ISSUE THREAD

**Issue by Aarav238** [cncf/glossary#1671] opened 2023-01-27 09:22 UTC
Page content - https://glossary.cncf.io/zero-trust-architecture/

`Zero Trust Architecture.md` is not available in hindi .

### Why this term needs to be updated?
- `Zero Trust Architecture` term available in English only but This term also needs to be Localized in Hindi.
- visit on page- https://glossary.cncf.io/zero-trust-architecture/

**Comment by mohitvdx** [comment] 2023-01-28 07:04
Hi I am new to the community. I can translate it to hindi language, though i dont know how to make it available on the glossary page. what should I do?

**Comment by Aarav238** [comment] 2023-01-28 09:53
Read the contribution guidelines @mohitvdx

**Comment by skushagra9** [comment] 2023-01-28 17:34
Hey @Aarav238 , I would love to work on this issue

**Comment by Aarav238** [comment] 2023-01-29 11:30
@skushagra9 I have already submitted the PR regarding this.

**Comment by Aarav238** [comment] 2023-01-29 11:31
@skushagra9  You should look into the website and check which terms are not localized yet , then raise issue regarding that term and Submit the PR about that.

**Comment by shivam-sharma7** [comment] 2023-01-31 03:38
hey @jihoon-seo i have already opened a PR for this 2 month ago #1387

**Comment by shivam-sharma7** [comment] 2023-01-31 03:40
#1387

**Comment by jihoon-seo** [comment] 2023-01-31 04:40
@shivam-sharma7 you are right.
This issue is a duplicate of #1354.

**Comment by Garima-Negi** [comment] 2023-02-07 07:14
This is a duplicate issue as @jihoon-seo has mentioned.

@Aarav238 Please go through open issues before creating new ones. Thank you.

**Closed by Garima-Negi** 2023-02-07 07:14 UTC
Labels: duplicate, lang/hi, hold
